site_name: DemaTrading.ai
nav:
    - Home: index.md
    - Getting Started:
        - Installation:
            - Installing: getting_started/installation/installation.md
            - Configuring Backtesting: getting_started/installation/configuring_backtest.md
            - Github Desktop: getting_started/installation/github_desktop.md
        - Platforms:
            - Installing on MacOS / Linux: getting_started/installation/mac_os.md
            - Installing on Windows: getting_started/installation/windows.md
            - Installing with M1 chip: getting_started/installation/mac_os_m1.md
        - Running:
            - Running The Engine (Docker): getting_started/running/running_docker.md
            - Running The Engine (Python): getting_started/running/running_python.md
        - Trading 101:
            - Trading Basics: getting_started/trading101/trading101.md
            - Termsheet: getting_started/trading101/termsheet.md
            - Contributing: getting_started/trading101/contributing.md
        - Strategies:
            - Strategy Examples: getting_started/strategies/strategyexamples.md
            - Advanced strategy creation: getting_started/strategies/advcreatingstrat.md
        - Backtesting:
            - Configuration: getting_started/backtesting/config.md
            - Backtesting arguments: getting_started/backtesting/arguments.md
            - Results: getting_started/backtesting/results.md
        - Experimental:
            - "[experimental] Hyperparameter optimization": getting_started/experimental/hyperopt.md
            - "[experimental] Installation": getting_started/experimental/executables.md

    - Getting Paid:
        - For algo creators: getting_paid/algocreatorpaid.md
        - For investors: getting_paid/investorpaid.md
    - Troubleshooting:
        - Strategy mistakes: troubleshooting/mistakes.md
        - Docker: troubleshooting/docker.md
        - FAQ: troubleshooting/troubleshooting.md
    - Changelog:
        - V0.1: changelog/v01.md
        - v0.2: changelog/v02.md
        - v0.3: changelog/v03.md
        - v0.4: changelog/v04.md
        - v0.5: changelog/v05.md
        - v0.6: changelog/v06.md
        - v0.7: changelog/v07.md
        - Major changes: changelog/majorchanges.md
        - Current known bugs: changelog/knownbugs.md

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
    custom_dir: custom-material/
    features:
        - navigation.expand
        - navigation.tabs
        - navigation.tabs.sticky
        - navigation.sections

    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
repo_name: dema-trading-ai/engine
repo_url: https://github.com/dema-trading-ai/engine
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: "#"
      separator: "-"
use_directory_urls: true
plugins:
    - mkdocs-video
