site_name: DemaTrading.ai
nav:
    - Home: index.md
    - 1 - Installation & Updating:
        - 1.1 Installation: installation_and_updating/installation.md
        - 1.2 Running: installation_and_updating/running.md
        - 1.3 Updating: installation_and_updating/updating.md
    - 2 - Your first strategy:
        - 2.1 Strategy explained: your_first_strategy/strategy_explained.md
        - 2.2 Running your first backtest: your_first_strategy/running_your_first_backtest.md
        - 2.3 Results explained: your_first_strategy/results_explained.md
        # - 2.4 Editing your buy and sell signal: TBC.md
        # - 2.5 Adjusting your Stoploss and ROI: TBC.md
        - 2.4 Editing your configuration: your_first_strategy/editing_your_configuration.md
    - 3 - Advanced options:
        - 3.1 Additional pairs: advanced_options/additional_pairs.md
        - 3.2 Hyperoptimalization: advanced_options/hyperoptimalization.md
    - 4 - Knowledge library:
        - 4.1 Trading Basics: knowledge_library/trading_basics.md
        - 4.2 Term sheet: knowledge_library/term_sheet.md
        # - 4.3 Finding strategy inspiration: TBC.md
        - 4.3 Troubleshooting: knowledge_library/troubleshooting.md
        - 4.4 FAQ: knowledge_library/faq.md
        - 4.5 Changelog: knowledge_library/changelog.md
    - 5 - Publishing your strategy:
        - 5.1 Publishing your strategy: publishing_your_strategy/publishing_your_strategy.md

theme:
    name: material
    nav_style: light
    logo: assets/logo.png
    favicon: assets/logo.png
    custom_dir: custom-material/
    features:
        - navigation.sections
        - navigation.top
        - navigation.indexes
    palette:
        # Light mode
        - media: "(prefers-color-scheme: light)"
          scheme: default
          primary: indigo
          accent: indigo
          toggle:
              icon: material/toggle-switch-off-outline
              name: Switch to dark mode

        # Dark mode
        - media: "(prefers-color-scheme: dark)"
          scheme: slate
          primary: blue
          accent: blue
          toggle:
              icon: material/toggle-switch
              name: Switch to light mode
repo_name: dema-trading-ai/engine
repo_url: https://github.com/dema-trading-ai/engine
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.tabbed
  - toc:
      permalink: "#"
      separator: "-"
  - attr_list
use_directory_urls: true
plugins:
    - mkdocs-video
    - search
extra:
  analytics:
    provider: google
    property: G-BKJF1ZT1TZ
  consent:
    title: Cookie consent
    description: >
      We use cookies to recognize your repeated visits and preferences, as well
      as to measure the effectiveness of our documentation and whether users
      find what they're searching for. With your consent, you're helping us to
      make our documentation better.