site_name: DemaTrading.ai
nav:
    - Home: index.md
    - Getting Paid:
      - Calculation example: calculationexample.md
      - For algo creators: algocreatorpaid.md
      - For investors: investorpaid.md
      - Termsheet: termsheet.md
    - Getting started:
        - Installation: installation.md
        - Trading 101: trading101.md
        - Strategy Examples: strategyexamples.md
        - Creating your own strategies: creatingstrat.md
        - Advanced strategy creation: advcreatingstrat.md
    - Troubleshooting:
      - Docker: docker.md
      - Strategy mistakes: mistakes.md
      - FAQ: troubleshooting.md
    - Changelog:
        - V0.1: v01.md
        - v0.2: v02.md
        - v0.3: v03.md
        - Major changes: majorchanges.md
        - Current known bugs: knownbugs.md

theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
repo_url: https://github.com/dema-trading-ai/engine
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      separator: "-"
