site_name: DemaTrading.ai
nav:
    - Home: index.md
    - Getting Paid:
      - Calculation example: calculationexample.md
      - For algo creators:
      - For investors:
      - Termsheet:
    - Getting started:
        - Installation: installation.md
        - Trading 101: 
        - Strategy Examples: strategyexamples.md
        - Creating your own strategies:
        - Advanced strategy creation:
    - Troubleshooting:
      - Docker:
      - Strategy mistakes:
      - FAQ: troubleshooting.md
    - Changelog:
        - V0.1: v01.md
        - v0.2:
        - v0.3:
        - Major changes:
        - Current known bugs:


theme:
    name: material
    logo: assets/logo.png
    favicon: assets/logo.png
repo_url: https://github.com/dema-trading-ai/engine
extra_css:
    - css/extra.css
markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - toc:
      permalink: "#"
      separator: "-"
