name: Docs Deployment Pipeline
on:
  push:
    branches: [main, development]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.x
      - run: pip install -r ./requirements.txt
      - name: Install Insiders Version of MkDocs Material
        run: |
          export TOKEN=${GH_TOKEN}
          pip install git+https://${TOKEN}@github.com/squidfunk/mkdocs-material-insiders.git
      - run: mkdocs gh-deploy --force
